### ISSUE TITLE
Update configuration to support both 

### ISSUE THREAD

**Issue by vrde** [TimDaub/slackchangelog#2]
I'd like to use Docker to containerize the app. AFAIK, a nice way to configure a containerized app is to use environment variables, but this is not supported right now because the the only way to configure the software is by using a file named `config.json` with all the keys/values for the configuration.

My proposal is to use [convict](https://github.com/mozilla/node-convict) to add support to environment variables. There is another npm module called [nconf](https://github.com/indexzero/nconf) that seems to be quite spread. I like `convict` because it also supports validation.

**Comment by TimDaub** [comment]
Sure, I wanted to do that anyways!
If you want to do it yourself, go ahead :)

**Comment by vrde** [comment]
[dotenv](https://github.com/motdotla/dotenv) seems quite interesting as well. I might go for this one.
